INSERT INTO public.positions (name, sort_number) VALUES ('Генеральный директор', 1);
INSERT INTO public.positions (name, sort_number) VALUES ('Коммерческий директор', 2);
INSERT INTO public.positions (name, sort_number) VALUES ('Финансовый директор', 3);
INSERT INTO public.positions (name, sort_number) VALUES ('Директор по продажам', 4);
INSERT INTO public.positions (name, sort_number) VALUES ('Технический директор', 5);
INSERT INTO public.positions (name, sort_number) VALUES ('Главный бухгалтер', 6);
INSERT INTO public.positions (name, sort_number) VALUES ('Начальник отдела снабжения', 7);
INSERT INTO public.positions (name, sort_number) VALUES ('Начальник отдела продаж', 8);
INSERT INTO public.positions (name, sort_number) VALUES ('Начальник транспортного отдела', 9);
INSERT INTO public.positions (name, sort_number) VALUES ('Начальник отдела маркетинга', 10);
INSERT INTO public.positions (name, sort_number) VALUES ('Начальник складского комплекса', 11);
INSERT INTO public.positions (name, sort_number) VALUES ('Бухгалтер', 12);
INSERT INTO public.positions (name, sort_number) VALUES ('Менеджер по закупкам', 13);
INSERT INTO public.positions (name, sort_number) VALUES ('Менеджер по продажам', 14);
INSERT INTO public.positions (name, sort_number) VALUES ('Кладовщик', 15);
INSERT INTO public.positions (name, sort_number) VALUES ('Грузчик', 16);
INSERT INTO public.positions (name, sort_number) VALUES ('Маркетолог', 17);
INSERT INTO public.positions (name, sort_number) VALUES ('Водитель', 18);
INSERT INTO public.positions (name, sort_number) VALUES ('Кассир', 19);
INSERT INTO public.positions (name, sort_number) VALUES ('Уборщица', 20);